spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=MusicManagement;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123456789
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: file:uploads/
server:
  port: 8080