spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=personal-playlist;encrypt=true;trustServerCertificate=true
    username: sa
    password:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8181